name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: RisingSunLight42
          template: classic
          base: header, activity, community, repositories
          config_timezone: Europe/Paris
          config_display: large
          # Achivements
          plugin_achievements: yes
          plugin_achievements_threshold: C
          # Activity
          plugin_activity: yes
          plugin_activity_timestamps: yes
          # Follow up issues and pull request
          plugin_followup: yes
          plugin_followup_sections: user
          # Coding habits
          plugin_habits: yes
          plugin_habits_from: 1000
          plugin_habits_days: 30
          plugin_habits_charts: yes
          # Isometric calendar
          plugin_isocalendar: yes